<div class="jumbotron">
    <h1><?php echo sprintf($this->translate('Welcome to %sZGTec Application %s'), '<span class="zf-green">', '</span>') ?></h1>
    <p><?php echo sprintf($this->translate('This is a home page of  %sZgApp Module for Zend Framework 2%s. <br/>You are currently running Zend Framework version %s.'), '<a href="javascript://">', '</a>', \Zend\Version\Version::VERSION) ?></p>
    <p></p>
</div>